Fix bug due to <= operator raising errors with native lists
File "[REDACTED]/lib/python3.7/site-packages/trajtrackerp/num2pos/_n2p_run.py", line 307, in play_success_sound
    sound_ind = np.where(endpoint_err_ratio <= exp_info.sounds_ok_max_ep_err)[0][0]
TypeError: '<=' not supported between instances of 'int' and 'list'